// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApL73D7lAlmw_8T7Nzc_dmD4p-USGjpMw',
    appId: '1:61077677736:web:243490cadbe7603556c49d',
    messagingSenderId: '61077677736',
    projectId: 'miaged-5c93a',
    authDomain: 'miaged-5c93a.firebaseapp.com',
    storageBucket: 'miaged-5c93a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLN9Xu8GxhX3KYr9lLOtO6DLVAoFdE5WA',
    appId: '1:61077677736:android:a71f4cbaec9c714656c49d',
    messagingSenderId: '61077677736',
    projectId: 'miaged-5c93a',
    storageBucket: 'miaged-5c93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcwBuCvkRQW1aFN5xVjyWNfQlxAer3Aw',
    appId: '1:61077677736:ios:190c16bb2d966fe956c49d',
    messagingSenderId: '61077677736',
    projectId: 'miaged-5c93a',
    storageBucket: 'miaged-5c93a.appspot.com',
    iosClientId: '61077677736-a1ongue7gki3l43k14pvv5ei7484aogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOcwBuCvkRQW1aFN5xVjyWNfQlxAer3Aw',
    appId: '1:61077677736:ios:190c16bb2d966fe956c49d',
    messagingSenderId: '61077677736',
    projectId: 'miaged-5c93a',
    storageBucket: 'miaged-5c93a.appspot.com',
    iosClientId: '61077677736-a1ongue7gki3l43k14pvv5ei7484aogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupName',
  );
}
